# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Harsaroop Dhillon
title: E. Engineer
email: harsaroopdhillon11@gmail.com


# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: "saroopi_314"
github_username: harsaroopdhillon

XMPP: hddhillon11@xmpp.jp

# Additional icon links
additional_links:
- title: estatefund.com
  icon: fas fa-globe

about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Harsaroop Dhillon. I am a recent graudate with a degree in Electrical Engineering and Physics. I am currently employed as a Software Engineer where I utilize languages such as C++ and C#. 

  I am most skilled in: , <mark>C</mark>, <mark>C++</mark>, <mark>C#</mark>, <mark>Node.JS</mark>, <mark>PHP</mark>, <mark>MySQL</mark>, <mark>Python</mark>, <mark>C#</mark>

content:


        
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      - layout: left
        border: weak    
        title: Startup
        caption: 2022 -
        sub_title: A startup that is currently in development.


      - layout: left
        border: weak    
        title: II-VI/Coherent Inc.
        caption: 2021-2022
        sub_title: Software Engineer
        
        
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: University of California, Berkeley
        caption: 2022 -
        sub_title: Project Management


      - layout: left
        title: San Jose State University
        caption: 2022
        sub_title: BS Electrical Engineering/Physics








  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak    
        title: SPEAR 
        description: | # this will include new lines to allow paragraphs
          A school team where we engaged in the design of a 1,000 lb-ft rocket in collaboration with the Naval Postgraduate School in Monterey, CA. 
          I designed the bulkhead, nosecone, and main bodytube of the rocket. Solidworks was used for the design, Ansys software was used for CFD
          
      
      - layout: left
        border: weak    
        title: 3D Printed Horn Array Antenna (2x1) 
        description: | # this will include new lines to allow paragraphs
          This was an RF project where I 3D printed a horn antenna. The calculations for the specifications for the horn antenna were done using numerical methods with a program I wrote in Python.
          A homemade desktop CNC milled 3dB hybrid coupler was also created. Used Microwave Office was used for the initial design of the coupler, HFSS was then used as FEM tool to verify. This was then exported to a Gerber file.
        
      - layout: left
        border: weak  
        title: Encryption Software 
        description: | # this will include new lines to allow paragraphs
          This was a project where I created a WebUI in AngularJS and the backend in PHP which would display the key for each user.  
          A Diffie-Hellman key exchange was implemented between the server and client. I interfaced with a high level Windows kernel driver, AFD.sys, to do networking from usermode

          
      - layout: left
        border: weak
        title: Burnout/Molding machine 
        description: | # this will include new lines to allow paragraphs
          This was a project where I used a Solid State Relay switch in conjunction with a thermocouple to make a burnout machine for 3D printed objects.


      - layout: left
        border: weak
        title: 200k Feet Rocket 
        description: | # this will include new lines to allow paragraphs
          This was a project where I built a solid fuel rocket that would cruise to an altitude of 200k feet (simulation was done with OpenRocket). 

      - layout: left
        border: weak
        title: 3D printed telescope
        description: | # this will include new lines to allow paragraphs
          This was a project where I created a dobsonian reflector telescope.

      - layout: left
        border: weak
        title: Antivirus Software 
        description: | # this will include new lines to allow paragraphs
          This was a project done I created while I was in high school. I developed the UI in C++ using the QT framework. I developed kernel mode drivers for network (TCP/IP stack), file system, registry, and ELAM for the Windows system. I designed a custom lexer/parser for my own signatures. 



      - layout: left
        border: weak
        title: Lane following Robot 
        description: | # this will include new lines to allow paragraphs
          This was a school project where we interfaced with IR Sensors on a robot using ARM (Cortex-M).
         
      - layout: left
        title: non-pipelined 8 bit CPU 
        description: | # this will include new lines to allow paragraphs
          This was a school project designed a non-pipelined 8 bit CPU in Verilog using Vivado by Xilinx

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        border: weak    
        title: TCAD-Augmented Machine Learning With and Without Domain Expertise
        link: https://ieeexplore.ieee.org/document/9419673
        # link_text: Project Website
        description: |
          In this research paper I utilized Machine Learning algorithims in Python on data generated by TCAD to simplify device physics properties.
  
      - layout: left
        border: weak           
        title: Simulation of Single-shot Qubit Readout of a 2-Qubit Superconducting System with Noise Analysis
        link: https://ieeexplore.ieee.org/document/9419673
        # link_text: Project Website
        description: |
          In this research paper I simplified the readout of a 2 Qubit System to see if it is possible to distingush multiple states in the presence of noise. I utilized HFSS and python throught this research. This was done in collaboration with Lawrence Livermore National Laboratory. 
         

      - layout: left
        border: weak    
        title: Study of MOSFET at cryogenic temperatures
        # link_text: Project Website
        description: |
          I implemented the Phillips model in Python to determine the effects of I vs V at very low temperatures.
         
         
         
      - layout: left
        border: weak    
        title: Processing of Semiconductor Wafer Data
        # link_text: Project Website
        description: |
          I took large data from a semiconductor wafer lab and processed it using interpolation algorithim for defects.
         
         
         
      - layout: left
        border: weak    
        title: FDTD approach, Schrodinger's equation
        # link_text: Project Website
        link: "Eight Bit Quantum Fourier Transform Using the FDTD Method"
        description: |
          I verified a published paper using Python. Implemented the FDTD algorithim to solve schrodinger's equation 
         
      - layout: left
        border: weak    
        title: Mobility study of MOS devices
        # link_text: Project Website
        description: |
          I used Machine Learning and TCAD to study various properties of MOS devices in an effort to simplify TCAD processes.  
         
      - layout: left
        title: Spectre/Meltdown CPU cache timing bugs
        # link_text: Project Website
        link: https://deepai.org/publication/meltdown
        description: |
          Published one of the first codes exploiting this bug for the Windows platform. 
        

        
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      some of my other interests and hobbies are:
      - Powerlifting
      - Hiking
      - Working on my startup.
      
      

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
